USE BOOKS_MANAGEMENT_SYSTEM
CREATE TABLE BOOKS_MAIN
(BNA CHAR(50) PRIMARY KEY,
BNU INT );



INSERT INTO BOOKS_MAIN VALUES ('数据结构', 10);
INSERT INTO BOOKS_MAIN VALUES ('操作系统', 10);
INSERT INTO BOOKS_MAIN VALUES ('LINUX的私房菜', 5);  
INSERT INTO BOOKS_MAIN VALUES ('信息安全法律基础', 4);
INSERT INTO BOOKS_MAIN VALUES ('数据库', 5);
